Development checkpoint.

diff --git a/sh/link/_ b/sh/link/_
--- a/sh/link/_
+++ b/sh/link/_
@@ -16,41 +16,42 @@
 # ln -s dir1/ dir2/
 
 
-  PATH="$PATH:$THIS_DIR/../sh_color/bin"
-  local +x ORIG="$(realpath --canonicalize-existing "$1")"
-  local +x DEST="$2"
-  local +x REAL_DEST="$(realpath --canonicalize-existing "$DEST")"
+PATH="$PATH:$THIS_DIR/../sh_color/bin"
+local +x ORIG="$(realpath --canonicalize-existing "$1")"
+local +x DEST="$2"
+local +x REAL_DEST="$(realpath --canonicalize-existing "$DEST" 2>/dev/null)"
 
-  if [[ -z "$ORIG" || -z "$DEST" ]]; then
-    exit 2
-  fi
+if [[ -z "$ORIG" || -z "$DEST" ]]; then
+  exit 2
+fi
 
-  if [[ -d "$DEST" ]]; then
-    DEST="$DEST/$(basename "$ORIG")"
-  fi
+if [[ -d "$DEST" ]]; then
+  DEST="$DEST/$(basename "$ORIG")"
+fi
 
-  # === Check if it already exists:
-  if [[ "$ORIG" == "$REAL_DEST" ||  "$ORIG" == "$(realpath --canonicalize-missing "$DEST")" ]]; then
-    echo "=== Already linked:" >&2
-    echo "$ORIG -> $DEST" >&2
-    return 0
-  fi
+# === Check if it already exists:
+if [[ "$ORIG" == "$REAL_DEST" ||  "$ORIG" == "$(realpath --canonicalize-missing "$DEST" 2>/dev/null)" ]]; then
+  echo "=== Already linked:" >&2
+  echo "$ORIG -> $DEST" >&2
+  return 0
+fi
 
-  if [[ -h "$DEST"  && ! -e "$DEST" ]]; then
-    echo "!!! Link exists, but is broken: " >&2
-    echo "$DEST -> "$(realpath --canonicalize-missing "$DEST")""
-    exit 2
-  fi
+if [[ -h "$DEST"  && ! -e "$DEST" ]]; then
+  echo "!!! Link exists, but is broken: " >&2
+  echo "$DEST -> "$(realpath --canonicalize-missing "$DEST")""
+  exit 2
+fi
 
-  local +x CMD="ln -s"
-  if [[ "$(stat -c %U "$(dirname "$DEST")" )" != "$USER" && ! -w "$(dirname "$DEST")" ]]; then
-    CMD="sudo $CMD"
-  fi
+if [[ "$(stat -c %U "$(dirname "$DEST")" )" != "$USER" && ! -w "$(dirname "$DEST")" ]]; then
+  echo "=== Running: sudo ln -s $ORIG $DEST" >&2
+  sudo /bin/ln -s "$ORIG" "$DEST"
+else
+  echo "=== Running: ln -s $ORIG $DEST" >&2
+  ln -s "$ORIG" "$DEST"
+fi
 
-  # --- IF it does NOT exit?
-  echo "=== Running: $CMD $ORIG $DEST" >&2
-  $CMD "$ORIG" "$DEST"
-  sh_color GREEN "--- Linked: $ORIG {{$DEST}}"
+# --- IF it does NOT exit?
+sh_color GREEN "--- Linked: $ORIG {{$DEST}}"
 
 
 
